hash-format = "sha256"

[[files]]
file = "mods/addadd.toml"
hash = "60acef8379dd63512b73dbbfc5eb8bfbd5552e081b233e8e41dc04af72ece6cd"
metafile = true

[[files]]
file = "mods/alaska-native-craft.toml"
hash = "786ab77f408a853f6b969eaff07e97d47bdb92800a52df60ca422090c4809634"
metafile = true

[[files]]
file = "mods/alternate-current.toml"
hash = "ea9317f689a57e604a3495f375980952f12f5b3d8a3f05a33655573eea068bcc"
metafile = true

[[files]]
file = "mods/architectury-fabric.toml"
hash = "a4f9d4a2bb6c3ca55085505462267d93e9f018d538cc2f14bd2b998ddf3a1f8d"
metafile = true

[[files]]
file = "mods/cem.toml"
hash = "84736dff13eb506b1cedcdb7a359bb0af143b987696e382e7502591d51c65ac2"
metafile = true

[[files]]
file = "mods/cit-resewn.toml"
hash = "4c4a87a05ed89f6a0a99b2783c9c4e9dfdaef462fed8ff88bd73d27da73d4ed5"
metafile = true

[[files]]
file = "mods/cloth-config.toml"
hash = "61a15f37dbaee42076eb50b29b17279561ef44ec14208db6790c0c0981723823"
metafile = true

[[files]]
file = "mods/completeconfig.toml"
hash = "5a34aa553fb6eb65203cfe6d85cbe7065cc41f8ee2b8d68e21c83f3264c880a9"
metafile = true

[[files]]
file = "mods/continuity.toml"
hash = "006a14c972eaeaea050b9e4e0d024f8782c2fe44e5f7a502eb392e9aa7793bae"
metafile = true

[[files]]
file = "mods/creeper-ai-updated.toml"
hash = "c82b9ad27aa7496db62408dfc1f3c0c7aa136357bd41ec18b0736118dc008b0f"
metafile = true

[[files]]
file = "mods/creeper-spores.toml"
hash = "1d258b06004a0929bc5a691fef78a85da33b8be794cf972c2057c81e92e83542"
metafile = true

[[files]]
file = "mods/culinaire.toml"
hash = "7326f21d7370b251aaed814b3b948d58052147eeddb0781f917b90243f0d8930"
metafile = true

[[files]]
file = "mods/custom-lan.toml"
hash = "3d1ae3b20ccd3ace88c82d1a6b33d98f3be4bb1ce9a818c5870902db3d573ba0"
metafile = true

[[files]]
file = "mods/dawn.toml"
hash = "1d341cffda3caea9911882a8c4508bc0934fe93563a6dd3c158aaf20f9ade07c"
metafile = true

[[files]]
file = "mods/dense-ores-refabricated.toml"
hash = "aabcd55a1ed65af055179335ab89a5439b65694eaba1c623fc5277aa0d119937"
metafile = true

[[files]]
file = "mods/ebe.toml"
hash = "c58834af10ab46edeb4946b55f4d71cf9bced4d37aef0ee122a5a7e4e9e17153"
metafile = true

[[files]]
file = "mods/effective.toml"
hash = "bf12203d7923bcc1060bbec8aaab382ebb3df9fb11575dace8aa6b6a68125fe7"
metafile = true

[[files]]
file = "mods/enhancedcraft.toml"
hash = "c1bc6df2af05e1fc494074d94e80908005c57caf45c56efb350dfa3cafb428ed"
metafile = true

[[files]]
file = "mods/extrasounds.toml"
hash = "050a98776edba8ef31bfacc43b281177415472e08674d9d030d57afe55085ca3"
metafile = true

[[files]]
file = "mods/fabric-api.toml"
hash = "d6dc8d5291fb8952048f7eb52951eec5fbabdac5554d93b55cd6e0ea4b9aeafa"
metafile = true

[[files]]
file = "mods/fabric-language-kotlin.toml"
hash = "7f4996fc7ac9367f157cbd94ac9b4601225279d457df78f66941a157e8592eb0"
metafile = true

[[files]]
file = "mods/feature-nbt-deadlock-be-gone.toml"
hash = "051c09e14638dc26c9f80ceb44facb5f3f2aa2d5aa352719748c3facd10a9ab3"
metafile = true

[[files]]
file = "mods/fwaystones.toml"
hash = "2b088474f731aa25c745a6a4258ef076c061f0eb374e1bbffd8896c315524002"
metafile = true

[[files]]
file = "mods/gimme-bundles.toml"
hash = "b49b3d6c76c4ca931eb7c83fd535892454c0a9751c39a81efa3ebfb9f8236974"
metafile = true

[[files]]
file = "mods/gldown.toml"
hash = "2c427789543f276864e54ae8fbfcb58c09b67b19fae65eb36e19381c956df84b"
metafile = true

[[files]]
file = "mods/indium.toml"
hash = "89f5ed5d28ea532046afeb96cb51ec7e450729e2e201011706cc0612a7d18c49"
metafile = true

[[files]]
file = "mods/kappa.toml"
hash = "6363596c5cb5959ee0905e42c305b27934f169e634eaffc6ca268623c2410915"
metafile = true

[[files]]
file = "mods/krypton.toml"
hash = "ffa430c24d8d6862b804c483a9070340fd3a89f858f8a5869b715534a06a04de"
metafile = true

[[files]]
file = "mods/lazydfu.toml"
hash = "da1b3ee71d9ed1f17da4c85ca3da39af3e49fcc5bb032689613c4e00fc587a40"
metafile = true

[[files]]
file = "mods/lithium.toml"
hash = "3fba2888b45044b8e058b6be4ffd8fe1241eace50004b76b6576dd5e78843a5a"
metafile = true

[[files]]
file = "mods/modern-industrialization.toml"
hash = "fdd2abd382aee68e2e69208ea291a0eb3c41f064aac21353998044c135c076fe"
metafile = true

[[files]]
file = "mods/no-null-processors.toml"
hash = "cacf5ebda915edc99213691d325e881db490b7420822bc3ae88fe1798a74a645"
metafile = true

[[files]]
file = "mods/ost-overhaul.toml"
hash = "162f7009a4dc7e1aa9d2a7815dad9f219a93ad22b97d11a283d3d9381bffe228"
metafile = true

[[files]]
file = "mods/owo-lib.toml"
hash = "311c934b34760781a319aab9fe3a2023c0854409afa155213a35b635290221f0"
metafile = true

[[files]]
file = "mods/promenade.toml"
hash = "d9cd1f64322e6ca67ac6e766a4d99b9b2368fc79f664fe08cf8cbe98ce7a5421"
metafile = true

[[files]]
file = "mods/repurposed-structures-fabric.toml"
hash = "8fd9c644ae6cd4da80f3987ab028927fb1c650dcaf76426720300ea425d8b369"
metafile = true

[[files]]
file = "mods/requiem.toml"
hash = "a7faafe5ffa629f1071c42bb9f3ef3dfefa5cf5f7c9be17ab04c789acb1e759b"
metafile = true

[[files]]
file = "mods/roughly-enough-items.toml"
hash = "693061bb93b6736bb42dcdac5832d28e79b97f6f42b16d982cc97e555f82a398"
metafile = true

[[files]]
file = "mods/secret-rooms.toml"
hash = "a7bb253ff643e90ef952677959ff1efc2acf000c4ca7f44ff80ba80722ab6ec3"
metafile = true

[[files]]
file = "mods/sky-villages.toml"
hash = "e752542fd8a134c8f37e13c37ee25adef79e538b12e1b223c2de65c2fcacea71"
metafile = true

[[files]]
file = "mods/sodium.toml"
hash = "1f04100ac9ec2dd3d54ad14b91fe5421549704f40e5a8447f842195a041facd8"
metafile = true

[[files]]
file = "mods/spark.toml"
hash = "f6b555e6f28ba0e86008ac48fa0b2971962e6a93f5a1b5e92dab0401e46e73dd"
metafile = true

[[files]]
file = "mods/starlight.toml"
hash = "3fba2d404a85b60f3f82e8014f2560dcf55cc62e5501309929171728e602de3e"
metafile = true

[[files]]
file = "mods/things.toml"
hash = "839b8571d282a0a1dc2401d18ca8332e332260cd73c553fdfe4b1d7794191b1b"
metafile = true

[[files]]
file = "mods/this-rocks.toml"
hash = "4fe8cb912adfc84d24df5b1e3db54bb7cff10159ad8550b50afcc58ef46d5c40"
metafile = true

[[files]]
file = "mods/tiefix.toml"
hash = "26d2dc9abe46668f6b884bde739d0faae776b956e87f2c13f253fdf1aa919083"
metafile = true

[[files]]
file = "mods/towers-of-the-wild-additions.toml"
hash = "a95326af97e290d97b9b9ecd8cd0a07751960dd567dda51a8175fcc3c31f8c4f"
metafile = true

[[files]]
file = "mods/trinkets.toml"
hash = "52e926b62a57b1c27163cafd914707491988ec25eca99afbd766465066feb988"
metafile = true

[[files]]
file = "mods/wthit.toml"
hash = "b72faa65a24166092664ace874c5a0b3ace10444804b22b8bf340bf9e4aaaefc"
metafile = true
