name = "Bibos Packwiz"
author = "piuvas"
version = "1.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b3bc81d93a9fb3e78d59a6ce01366bc5977ae3961b8358ec07555d9bbebfa71e"

[versions]
fabric = "0.12.12"
minecraft = "1.18.1"

[options]
acceptable-game-versions = "1.18"
