name = "Bibos Packwiz"
author = "piuvas"
version = "1.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9debcf86fc86c6b87d7e8d3d54abc362c46baff771fa8c00d1c768b44f4c613f"

[versions]
fabric = "0.12.12"
minecraft = "1.18.1"

[options]
acceptable-game-versions = "1.18"
