name = "Bibos Packwiz"
author = "piuvas"
version = "1.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "75f20c3b73594afc8364a01203e9a84686c869a06a408791ecb20a31702b78e8"

[versions]
fabric = "0.12.12"
minecraft = "1.18.1"

[options]
acceptable-game-versions = "1.18"
