name = "Bibos Packwiz"
author = "piuvas"
version = "1.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b29ae778563e7dd87c5d5db7852c3374b96cdc23f29c2816d467d5a5f29e65f6"

[versions]
fabric = "0.12.12"
minecraft = "1.18.1"

[options]
acceptable-game-versions = "1.18"
