name = "Bibos Packwiz"
author = "piuvas"
version = "1.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a647bbad14db5393707fcc904b169b684ce68e1aec910bc66b06677614aea686"

[versions]
fabric = "0.12.12"
minecraft = "1.18.1"

[options]
acceptable-game-versions = "1.18"
