name = "CompleteConfig"
filename = "completeconfig-lib-1.3.3.jar"
side = "both"

[download]
url = "https://cdn.modrinth.com/data/GtqG8z1h/versions/1.3.3/completeconfig-lib-1.3.3.jar"
hash-format = "sha512"
hash = "8576ce286592401851d4753ecd5d9a836f7619e3054324acda5b09aab3b2de3ddb0dc1c1698727b430cc6e8195b4dda021cf8b193a677c8ebd9171dc1943a09f"

[update]
[update.modrinth]
mod-id = "GtqG8z1h"
version = "MP74VKN8"
