name = "Creeper Spores"
filename = "creeper-spores-1.7.2.jar"
side = "both"

[download]
url = "https://cdn.modrinth.com/data/WSdgoMoj/versions/1.7.2/creeper-spores-1.7.2.jar"
hash-format = "sha512"
hash = "78e48890a7c7c7dbfaf5e0c6a62c177ea8e33e07ba75c21c7eb88d5d3f2b187282caf959c84ff3e67753bb07b02d65663dd2157ddc10f353908c669489af431d"

[update]
[update.modrinth]
mod-id = "WSdgoMoj"
version = "SyUw85OT"
