name = "Creeper AI Updated"
filename = "creeperaiupdated-fabric-1.5.0.jar"
side = "both"

[download]
url = "https://cdn.modrinth.com/data/YnAkda0q/versions/1.5.0/creeperaiupdated-fabric-1.5.0.jar"
hash-format = "sha512"
hash = "1a28f946451a1080cbd4469cdb0d25818a4d24deefd65a6f5fd7c34118abd3336903bcf3d654a968a67ba1676a6355382bb3c1610cb47f73b909c9646076f660"

[update]
[update.modrinth]
mod-id = "YnAkda0q"
version = "IRCDI5zT"
