name = "ExtraSounds"
filename = "extrasounds-2.2.0+1.18.jar"
side = "client"

[download]
url = "https://cdn.modrinth.com/data/uPWCQrVL/versions/2.2.0+1.18/extrasounds-2.2.0+1.18.jar"
hash-format = "sha512"
hash = "dba1626c108bade01cbfd49ee95a9a2065d52f3197f00968a0da4726a6635b6ea9287421ca31ad6895fdceac5db4050d1d38988965de1cde9f2a26bf625f40f2"

[update]
[update.modrinth]
mod-id = "uPWCQrVL"
version = "jHCuPXTd"
