name = "Modern Industrialization"
filename = "Modern-Industrialization-1.0.4.jar"
side = "both"

[download]
url = "https://cdn.modrinth.com/data/Gov5Dboq/versions/1.0.4/Modern-Industrialization-1.0.4.jar"
hash-format = "sha512"
hash = "0fafd090ea09e6b61d1f09b4028f3b6f8083fc743f66065cc60e796ba95636b1313ec56efc871a913d9da338918007c559e890462a0db4494019d87b3c9d4480"

[update]
[update.modrinth]
mod-id = "Gov5Dboq"
version = "I5tCkOxx"
