name = "oÏ‰o (owo-lib)"
filename = "owo-lib-0.5.1+1.18.jar"
side = "both"

[download]
url = "https://cdn.modrinth.com/data/ccKDOlHs/versions/0.5.1+1.18/owo-lib-0.5.1+1.18.jar"
hash-format = "sha512"
hash = "a7988467a4c48a0e14b67f7d290fb528f781b6e7b02bd4611397dfcdd4ca3f4c641734bc7a4d2368163c0829b5d9d5d4126efb3df1ff675587305f05e34ceda9"

[update]
[update.modrinth]
mod-id = "ccKDOlHs"
version = "q3Sxg4SA"
