name = "Plasmo Voice"
filename = "plasmovoice-fabric-1.18.1-1.2.10-alpha.jar"
side = "both"

[download]
url = "https://cdn.modrinth.com/data/1bZhdhsH/versions/fabric-1.18-1.2.10-alpha/plasmovoice-fabric-1.18.1-1.2.10-alpha.jar"
hash-format = "sha512"
hash = "3faac8b3b103fb3b3a66ee6b8c1c86c2de34e71693f72c0e94b79a863cd20e4105567e4a3a53459ed43b43dbe4fdbd09dc9f56bfc6ab8ab0f759f6750f79268a"

[update]
[update.modrinth]
mod-id = "1bZhdhsH"
version = "XQrCilqk"
