name = "Promenade"
filename = "promenade-2.5.1.jar"
side = "both"

[download]
url = "https://cdn.modrinth.com/data/GuE5FpvB/versions/2.5.1/promenade-2.5.1.jar"
hash-format = "sha512"
hash = "ccea93c4eb77847604c08f7365ad47beee40c359edfefa7364827677aafbc760c2611a3b827e02e38efc1ca1517b6f4fbef4f7a73d4f064074cff1b74df3e813"

[update]
[update.modrinth]
mod-id = "GuE5FpvB"
version = "s2r6UFMr"
