name = "Promenade"
filename = "promenade-2.4.0.jar"
side = "both"

[download]
url = "https://cdn.modrinth.com/data/GuE5FpvB/versions/2.4.0/promenade-2.4.0.jar"
hash-format = "sha512"
hash = "69305e57330f18124d59c8a26dcc25a637438303edf28c94ca6b07deb0e5e8da20d28f4802e6b4f534c8ce7e8f7c55848bb6bdf1b30cbdbe9ae7cdd3301f09b2"

[update]
[update.modrinth]
mod-id = "GuE5FpvB"
version = "hPETOKUD"
