name = "Repurposed Structures - Fabric"
filename = "repurposed_structures_fabric-3.3.1+1.18.1.jar"
side = "both"

[download]
url = "https://cdn.modrinth.com/data/muf0XoRe/versions/3.3.1+1.18.1/repurposed_structures_fabric-3.3.1+1.18.1.jar"
hash-format = "sha512"
hash = "e4dd07bfc1be0b22ead49d27108df1d0586ffb1a6d62814cd2c3ab361ccd9df8d9b82abb398a4459e4a31da9e0ce273070c944fd6d20570d74d8025e6a4caed6"

[update]
[update.modrinth]
mod-id = "muf0XoRe"
version = "7UyHjyWS"
