name = "Repurposed Structures - Fabric"
filename = "repurposed_structures_fabric-3.3.0+1.18.1.jar"
side = "both"

[download]
url = "https://cdn.modrinth.com/data/muf0XoRe/versions/3.3.0+1.18.1/repurposed_structures_fabric-3.3.0+1.18.1.jar"
hash-format = "sha512"
hash = "7c04b3862c69d099d5d145499c0bedb027d7f7f3441597f68c452ccb1c01b86d4fbc13084723ac3663d548af9f6f75c16c8c371342b97f657ae10e1cb5db8cf6"

[update]
[update.modrinth]
mod-id = "muf0XoRe"
version = "ADfl8WUh"
