name = "Repurposed Structures - Fabric"
filename = "repurposed_structures_fabric-3.3.11+1.18.1.jar"
side = "both"

[download]
url = "https://cdn.modrinth.com/data/muf0XoRe/versions/3.3.11+1.18.1/repurposed_structures_fabric-3.3.11%2B1.18.1.jar"
hash-format = "sha512"
hash = "774b9f9b78ae3b477211041b231cd1ad45d52ad171aa76b2f09d57d8c22380c06c53fd27238a349e29baac9cea8d50d95d8d5d694337eeca7be0ba42ae324d9f"

[update]
[update.modrinth]
mod-id = "muf0XoRe"
version = "bknOqCHj"
