name = "Repurposed Structures - Fabric"
filename = "repurposed_structures_fabric-3.3.9+1.18.1.jar"
side = "both"

[download]
url = "https://cdn.modrinth.com/data/muf0XoRe/versions/3.3.9+1.18.1/repurposed_structures_fabric-3.3.9%2B1.18.1.jar"
hash-format = "sha512"
hash = "a4ed09964a29127f19558ca8bdc6827571573376bf19f0e19eb2ed0a55530ee7a9b55e4ec28689e99f4ccbb23779748156e7e91219b49458940eb4f323b49031"

[update]
[update.modrinth]
mod-id = "muf0XoRe"
version = "hfIaM0WR"
