name = "Requiem"
filename = "requiem-2.0.0-beta.7.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3639/233/requiem-2.0.0-beta.7.jar"
hash-format = "murmur2"
hash = "2826806343"

[update]
[update.curseforge]
file-id = 3639233
project-id = 265729
