name = "Requiem"
filename = "requiem-2.0.0-beta.5.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3574/843/requiem-2.0.0-beta.5.jar"
hash-format = "murmur2"
hash = "3189139755"

[update]
[update.curseforge]
file-id = 3574843
project-id = 265729
