name = "Secret Rooms"
filename = "secretrooms-1.3.0+1.18.1.jar"
side = "both"

[download]
url = "https://cdn.modrinth.com/data/AKgnrAFj/versions/130/secretrooms-1.3.0%2B1.18.1.jar"
hash-format = "sha512"
hash = "4b4705101acfd47bbea223e46787836c44f4eecb63268ee4dea316d102b211ddfac747ec46335478504b78c3a66abf63537d36673f9e1278601ebea7c292ee77"

[update]
[update.modrinth]
mod-id = "AKgnrAFj"
version = "n9sVzRT5"
