name = "Secret Rooms"
filename = "secretrooms-1.2.0+1.18.1.jar"
side = "both"

[download]
url = "https://cdn.modrinth.com/data/AKgnrAFj/versions/120/secretrooms-1.2.0+1.18.1.jar"
hash-format = "sha512"
hash = "809179dd5d20c7fc3bde0b1242631ecd91bb23bbf0a0ac8003edc18a08fc0da5626dfd5e48afd245b926fd5857eeec2720c5f160a1213a57d98398634e1af53e"

[update]
[update.modrinth]
mod-id = "AKgnrAFj"
version = "1BmFebMQ"
