name = "Things"
filename = "things-0.2.15+1.18.jar"
side = "both"

[download]
url = "https://cdn.modrinth.com/data/VzAGdu9D/versions/0.2.15+1.18/things-0.2.15%2B1.18.jar"
hash-format = "sha512"
hash = "430ddfb720dfe5f0fa7520021be44383df0e64435c39b44fbd7aafc47e03fbf34e3c67e46b51979ac5f8370326514694aaad75dd0d65871433f0abacc6fec540"

[update]
[update.modrinth]
mod-id = "VzAGdu9D"
version = "e2ysxVmj"
