name = "Things"
filename = "things-0.2.12+1.18.jar"
side = "both"

[download]
url = "https://cdn.modrinth.com/data/VzAGdu9D/versions/0.2.12+1.18/things-0.2.12+1.18.jar"
hash-format = "sha512"
hash = "501f8507b142446e1fc7af2fc4eb41b0a3b064f4919e314f48a09d38c8fc32700a74220d5a17e8ad2d9e85c36558de567e50a9c5defd70ceb14b8b32a5c3289c"

[update]
[update.modrinth]
mod-id = "VzAGdu9D"
version = "ylZli2mA"
