name = "This Rocks!"
filename = "rocks-1.5.2.jar"
side = "both"

[download]
url = "https://cdn.modrinth.com/data/Sb5ypgDP/versions/1.5.2/rocks-1.5.2.jar"
hash-format = "sha512"
hash = "f5598a30fd529ebbcc837ce38ffbfa974813b98334dd610e778858146620e08ba310e6f1368c8546698564a34e064ec28e87bd55fa464bbc0edfd63096308b00"

[update]
[update.modrinth]
mod-id = "Sb5ypgDP"
version = "hInTt4XW"
