name = "Victus - Custom Hearts"
filename = "victus-0.1.6+1.18.jar"
side = "both"

[download]
url = "https://cdn.modrinth.com/data/Sy5mAKPK/versions/0.1.6+1.18/victus-0.1.6+1.18.jar"
hash-format = "sha512"
hash = "18864649af2734b20ac00b1802ae54601e461ada145af8733d178b3ba25d89a248fd80f5981e0ac0aa20beff2efb288ad8694237327fd58120edbf8c028ef57e"

[update]
[update.modrinth]
mod-id = "Sy5mAKPK"
version = "6SleTTcQ"
