name = "Very Many Players (Fabric)"
filename = "vmp-fabric-mc1.18.1-0.2.0+beta.2.18-all.jar"
side = "both"

[download]
url = "https://cdn.modrinth.com/data/wnEe9KBa/versions/0.2.0+beta.2.18 1.18.1/vmp-fabric-mc1.18.1-0.2.0+beta.2.18-all.jar"
hash-format = "sha512"
hash = "9ab1663e80757ee3e51102a3a104d061c7b902a6064d6710b3de492467a2831490ffbe88effea27829b983ebd0fbb9a144e670896bef412d6bb86aeb0096792c"

[update]
[update.modrinth]
mod-id = "wnEe9KBa"
version = "xZyKz0JY"
